(** Builds an AST of {!Node}s from {!Token}s. *)

(** Raised if an invalid token is encountered. *)
exception InvalidToken of string

(** Constructs an AST (which is really just a {!Node.t} list).

    Arguments:
    - a {!Token.t} list (generated by {!Lexer.tokenize}).
    - an accumulator (e.g., an empty {!Node.t} list).

    Returns: A {!Node.t} list.

    For example, if [tokens] is a list of tokens returned by
    {!Lexer.tokenize}, construct an AST from it with:
    [let nodes = build tokens []]. *)
val build : Token.t list -> Node.t list -> Node.t list
