(** Utility for pretty printing AST nodes. *)

(** Generate a {!Tty_str.t} list from a {!Node.t} list.

    Arguments:
    - A {!Node.t} list (e.g., generated by {!Ast.build}).

    Returns: a {!Tty_str.t} list.

    For example, suppose [nodes] is a list of nodes generated from
    {!Ast.build}. Then [pprint nodes] will return a list of {!Tty_str}
    strings that can be printed to a TTY or other target. *)	    
val pprint : Node.t list -> Tty_str.t list
