(** A utility for printing test results.

    This module constructs the primary output of the program.
    When the user runs this program (the executable) and it prints
    out a bunch of lines of text to the screen, that list of lines
    is precisely the list of lines generated by the [pprint] function
    of this module.

    Any other pretty-printing modules are meant for other pretty-printing
    purposes, like verbosity/debugging/errors. *)

(** Raised when a result is invalid. *)
exception InvalidResult of string

(** This funtion takes two arguments: a {!Result.t} list, and a [bool]
    indicating if those results succeeded or failed. It then generates a
    {!Tty_str.t} list.

    Arguments:
    - A {!Result.t} list (e.g., generated by {!Eval.run}).
    - A [bool] indicating if the provided {!Result.t} list as a whole
    succeeded or failed.

    Returns: A {!Tty_str.t} list.

    For example, suppose [results] is a list of result nodes generated by
    {!Eval.run}, and suppose those [results] as whole succeeded. Then
    [pprint results true] will return a {!Tty_str.t} list that represents
    the textual output of the results, which can be printed to a TTY
    or other target. *)
val pprint : string -> Result.t list -> bool -> Tty_str.t list
