(** Utility for printing tokens. *)

(** Generate a {!Tty_str.t} list from a {!Token.t} list.

    Arguments:
    - A {!Token.t} list (e.g., generated by {!Lexer.tokenize}).

    Returns: a {!Tty_str.t} list.

    For example, if [tokens] is a list of tokens generated by
    {!Lexer.tokenize}, then [pprint tokens] will generate a list of
    {!Tty_str} strings that can be printed to a TTY or other target. *)
val pprint : Token.t list -> Tty_str.t list
